name: adcolony_flutter
description: Adcolony SDK for Android & iOS
version: 1.8.0+1
homepage: https://github.com/arnavvaryani/flutter_plugins

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:

  plugin:
    platforms:
      android:
        package: com.anavrinapps.adcolony_flutter
        pluginClass: AdcolonyFlutterPlugin
      ios:
        pluginClass: AdcolonyFlutterPlugin
