name: flutter_ayetstudios
description: A new flutter plugin project.
version: 1.0.0
homepage: https://github.com/anavrinapps/flutter_plugins

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.anavrinapps.flutter_ayetstudios
        pluginClass: FlutterAyetstudiosPlugin
      ios:
        pluginClass: FlutterAyetstudiosPlugin

