name: flutter_inbrain
description: Inbrain surveys for Android & iOS
version: 1.3.2
homepage: https://github.com/AnavrinApps/flutter_plugins 

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.anavrinapps.flutter_inbrain
        pluginClass: FlutterInbrainPlugin
      ios:
        pluginClass: FlutterInbrainPlugin

